### PR TITLE
Add ability to merge state in when adding store.

### PR DESCRIPTION
**Pull request by foiseworth**

### CODE REVIEW

**Comment by glenjamin** [comment]
Hrm, I was thinking this would be implicit, as the dispatcher already has the current state

**Comment by glenjamin** [comment]
If we want an opt-out, can provide a removeStore method

**Comment by foiseworth** [comment]
Implicit is certainly better. Should I add removeStore when we first use it?

**Comment by glenjamin** [comment]
Yeah, no removeStore for now.

Can you use `in` for the check so falsy values are preserved?

**Comment by foiseworth** [comment]
No problem - done

**Comment by glenjamin** [comment]
Cheers, will merge this but would like at least one test covering this case.

**Comment by glenjamin** [comment]
published as `v0.4.0`

**Pull request merged**
